### ISSUE TITLE
High CPU usage when more than 5 clients connect or 5 sources active

### ISSUE THREAD

**Issue by barlowd55** [pecop2/iptv_multicast_udp_proxy_streaming#1]
I really love your multicast project. The only concern is that if more than 5 clients connect or if more than 5 sources are active, the CPU usage reaches more than 50-60 percent. 

Any way to reduce the CPU usage to atleast accommodate 100-200 clients? This is with no transcode and plain restream. 

My server is i7 processor.

**Comment by pecop2** [comment]
Interesting to hear that someone find it useful.
It was not developed with that in mind, but good concern here, now I am curious what actually uses the CPU that much.
At this moment not sure though, might be the VLC players or the threaded stream and request handlers or both.

**Comment by barlowd55** [comment]
Glad you replied. I am trying multiple option for my church streaming project. Yours is much better to recast to many clients through our customized app. 
Is there a way to find the root cause?. I have read online that VLC shouldn't be taking so much CPU load, if it is not transcoding, but there is still encoding - decoding going on. 
Let me know happy to work with you on the project if you have the time.

**Comment by pecop2** [comment]
You are trying to recast the same stream, right? It that's the case, the VLC players are not the problem, because if the requests from the clients are the same (same url, same stream), only one VLC player is started. We should seek the problem elsewhere.

**Comment by barlowd55** [comment]
Ok - I will give you 2-screenshots- Both scenarios the CPU usage is high. RAM is significantly less.

1. This is 1-stream with 9-active clients

![Screenshot 2021-11-15 13 46 54](https://user-images.githubusercontent.com/94359831/141785495-11b7df1c-eab0-4717-a248-e9e2689f7d54.png)

2. This is 9-streams with 1-active client

![Screenshot 2021-11-15 13 50 24](https://user-images.githubusercontent.com/94359831/141785518-83039399-49cd-44c8-a33e-ba39d51f2e70.png)

Let me know your thoughts.

**Comment by barlowd55** [comment]
More digging, it seems like a miscalculation from my end. I was calculating the actual CPU percentage that the python script took, but the overall load was barely 6-9% of multi-core functionality (CPU USAGE%). 

But still you can provide your thoughts on the above.

**Comment by pecop2** [comment]
The scenarios are actually good to compare, because they confirm that the VLC players do not increase CPU usage. The scenario with 9-streams 1-client, there are 9 different VLC players running and the other scenario, only 1 VLC player, but the CPU usage is comparable. From this I can conclude that the threaded handlers are the ones contributing to the CPU usage. There is something to be done, with no guarantees that it would decrease CPU usage though. 
Is the 6-9% satisfactory? I am curious now how my code would perform to be honest. :D

**Comment by barlowd55** [comment]
I won't say 6-9% is good enough, but definitely if you can get the thread handlers to settle down more on the CPU, it will be helpful. 

Usually if you use FFMPEG, the scenario will be quite better with additional performance gain, but the downside is to setup a separate multicast server, while VLC is an all-in-one formula and also works on-demand (activate only when a client connects).

I have deployed your code in production so we should see how it performs in real-scenario. The 6-10% will not make a difference because I do not have much clients connecting, just about 100 maybe (NOT AT GIVEN TIME).  So whatever the code refactor you make, it will be helpful.

**Comment by pecop2** [comment]
Well said and quite interesting. VLC was the simplest approach in my eyes. I'll see what I can do about it...

**Comment by barlowd55** [comment]
Also I think you also need to incorporate a use-case, if the source is down, the script keeps on retrying, and does not exit. This is major source of high cpu / memory. More like you call it zombie process. You can add a max retry polling option of 5 sec, if no response from source, stop the thread. 

Glad you accepted the feedback. Hope to see your magic, and your approach is very interesting compared to the rest. Keep it up.

**Comment by pecop2** [comment]
Maybe you can combine this, but use udpxy instead of my "proxy". CPU usage of my "proxy" is high as I have seen during my short tests. Tried something, but with no success in reducing CPU usage, with <20 users there were surges of up to 25% usage  :|
I hoped that the socket timeout of 10 seconds would do the trick if there is no response from the source. 
Only the VLC player should retry infinitely, but if the receiving socket times out after 10 sec, it would throw an exception, essentially stopping the thread. But if the client retries, then new thread starts and so on..
So at this moment no idea what to do.

**Comment by barlowd55** [comment]
Ok I am not sure what you mean by use udpxy. What I have done is simply pulled latest from git and ran the python script. So I am assuming UDPXY is activated by default or should I be adding the udpxy port in my client? 

Anyways, I tried the code again and CPU usage is still the same going about 50-55% for 9 active streams. RAM management is really good this time and I can see faster streaming on my server, so better performance gain here. 

![Screenshot 2021-11-16 23 53 10](https://user-images.githubusercontent.com/94359831/142137367-7104f24a-bd8c-493e-98c0-2cd7b20c176c.png)

Let me know if you want me to test differently.

**Comment by barlowd55** [comment]
Anyway to incorporate a third-party proxy server:
https://github.com/abhinavsingh/proxy.py
May help

**Comment by pecop2** [comment]
> Ok I am not sure what you mean by use udpxy. What I have done is simply pulled latest from git and ran the python script. So I am assuming UDPXY is activated by default or should I be adding the udpxy port in my client?
> 

udpxy.com, but than you'd have that running separately, and must reconfigure the code to run with that proxy instead. Just mentioning it as an option. 

For the third party proxy, not sure how it would behave with UDP video streams.

**Comment by barlowd55** [comment]
UDPXY looks cool project, any way to use UDPXY as the proxy instead. Your help will be appreciated.

**Comment by pecop2** [comment]
You should start it on the server and than only modify the port of the UDPXY in the app. The built-in one should not be started.

**Comment by barlowd55** [comment]
So if I am understanding correctly, I just need to setup the udpxy app and then update the udpxy port in the python script? 

Do I need to do anything to not use the built-in proxy server?

**Comment by pecop2** [comment]
Adapting the MTU decreased CPU usage greatly.

**Comment by barlowd55** [comment]
yes the issue is fixed now. So closing this issue.
